---
deployment:
  tasks:
    - composer install --no-dev --optimize-autoloader
    - npm ci
    - npm run build
    - php artisan key:generate --force
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
